Attempt to fix OSX build on Travis
On Travis git seems to be installed already:

$ if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install git qt5; fi
Error: git-2.10.0 already installed

which is causing the build to fail.